### ISSUE TITLE
file not exists which is referenced

### ISSUE THREAD

**Issue by SiddiqueAhmad** [mageplaza/magento-2-ajax-layered-navigation#2]
https://github.com/mageplaza/magento-2-ajax-layered-navigation/blob/02733fa19c3b745d658ed84148bfb354545b9da6/view/frontend/layout/catalogsearch_result_index.xml#L32

**Comment by Tuvpt** [comment]
Thank you for your suggestions.
We will fix it. Please remove it to avoid affecting your page
