### ISSUE TITLE
Uncaught ReferenceError: mageplazaSearchProducts is not defined

### ISSUE THREAD

**Issue by mariogobos** [mageplaza/magento-2-ajax-layered-navigation#21]
After i install porto template in magento 2.4.2 every product has this error in console page. The only way to delete the error is to disable Search in magento configuration under mageplaza exstensions.

**Comment by Uri-Mageplaza** [comment]
Hello, 
I'm Uri from Mageplaza Support Team.

Currently, the Porto module version is probably no longer compatible with the Magento version you are using.
Please submit your ticket at the following address: https://mageplaza.freshdesk.com/a/tickets/new
We will send you the latest version matching your Magento Version.

Best Regards,
Uri

**Comment by mariogobos** [comment]
Thanks a lot, i've open the ticket.
